### ISSUE TITLE
ホームタイムラインを見ようとするとエラーが出ることがある

### ISSUE THREAD

**Issue by rinsuki** [MissKernel/Misskey-Web#78]

**Comment by rinsuki** [comment]
モバイル版
エラーメッセージ

```
技術的な問題が発生しています。
詳細情報
TypeError: Cannot read property 'common' of undefined
    at Object.jade_mixins.core.jade_interp [as core] (eval at <anonymous> (/var/misskey-web/node_modules/misskey-web/node_modules/jade/lib/index.js:218:8), <anonymous>:29:386)
    at Object.jade_mixins.post.jade_interp [as post] (eval at <anonymous> (/var/misskey-web/node_modules/misskey-web/node_modules/jade/lib/index.js:218:8), <anonymous>:66:20)
    at eval (eval at <anonymous> (/var/misskey-web/node_modules/misskey-web/node_modules/jade/lib/index.js:218:8), <anonymous>:235:20)
    at eval (eval at <anonymous> (/var/misskey-web/node_modules/misskey-web/node_modules/jade/lib/index.js:218:8), <anonymous>:247:4)
    at eval (eval at <anonymous> (/var/misskey-web/node_modules/misskey-web/node_modules/jade/lib/index.js:218:8), <anonymous>:259:881)
    at res (/var/misskey-web/node_modules/misskey-web/node_modules/jade/lib/index.js:219:38)
    at Object.exports.renderFile (/var/misskey-web/node_modules/misskey-web/node_modules/jade/lib/index.js:380:38)
    at Object.exports.renderFile (/var/misskey-web/node_modules/misskey-web/node_modules/jade/lib/index.js:370:21)
    at View.exports.__express [as engine] (/var/misskey-web/node_modules/misskey-web/node_modules/jade/lib/index.js:417:11)
    at View.render (/var/misskey-web/node_modules/misskey-web/node_modules/express/lib/view.js:126:8)
    at tryRender (/var/misskey-web/node_modules/misskey-web/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/var/misskey-web/node_modules/misskey-web/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/var/misskey-web/node_modules/misskey-web/node_modules/express/lib/response.js:961:7)
    at res.locals.display (/var/misskey-web/node_modules/misskey-web/built/call-controller.js:94:13)
    at /var/misskey-web/node_modules/misskey-web/built/sites/mobile/pages/home/controller.js:6:20
    at process._tickCallback (node.js:401:9)
```

**Comment by syuilo** [comment]
デスクトップ版でも見れなくなる事がありますか？
