### ISSUE TITLE
gulp buildでError: Parsing file (path)/src/web/desktop/common/scripts/timeline-core.ls: Unexpected token (8:77)

### ISSUE THREAD

**Issue by rinsuki** [MissKernel/Misskey-Web#92]
# Full Error Log

```
[07:02:44] Failed to load external module ts-node/register
[07:02:44] Failed to load external module typescript-node/register
[07:02:44] Failed to load external module typescript-register
[07:02:44] Requiring external module typescript-require
[07:02:49] Using gulpfile /var/misskey-clone/build/Misskey-Web/gulpfile.ts
[07:02:49] Starting 'build:ts'...
[07:02:49] Starting 'copy:bower_components'...
[07:02:49] Starting 'build:frontside-scripts'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Parsing file /var/misskey-clone/build/Misskey-Web/src/web/desktop/common/scripts/timeline-core.ls: Unexpected token (8:77)
    at Deps.parseDeps (/var/misskey-clone/build/Misskey-Web/node_modules/module-deps/index.js:452:28)
    at fromSource (/var/misskey-clone/build/Misskey-Web/node_modules/module-deps/index.js:389:44)
    at /var/misskey-clone/build/Misskey-Web/node_modules/module-deps/index.js:383:17
    at ConcatStream.<anonymous> (/var/misskey-clone/build/Misskey-Web/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/var/misskey-clone/build/Misskey-Web/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (/var/misskey-clone/build/Misskey-Web/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at ConcatStream.Writable.end (/var/misskey-clone/build/Misskey-Web/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at DuplexWrapper.onend (/var/misskey-clone/build/Misskey-Web/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:495:10)
```

**Comment by rinsuki** [comment]
LiveScriptからJavaScriptへのコンパイル処理が抜けているように見えますが（間違っていたら申し訳ありません）

**Comment by syuilo** [comment]
@Petitsurume https://github.com/MissKernel/Misskey-Web/blob/master/package.json#L24

**Comment by rinsuki** [comment]
@syuilo oh,sorry

**Comment by syuilo** [comment]
内部的なデバッグ作業の結果、`module-deps`に以下のようなコードが渡されていることが判明しました。

``` javascript
// Generated by LiveScript 1.4.0
var $, Sortable, uploadFile, sncompleter, postContentInitializer, postCompiler, subPostCompiler, AlbumDialog, userCard, Post, Timeline;
$ = require("./..\\..\\..\\..\\..\\bower_components\\jquery\\dist\\jquery");
require("./..\\..\\..\\..\\..\\bower_components\\jquery.transit\\jquery.transit.js");
Sortable = require("./..\\..\\..\\..\\..\\bower_components\\Sortable\\Sortable.js")
require("./..\\..\\..\\..\\..\\bower_components\\Sortable\\ng-sortable.js")
require("./..\\..\\..\\..\\..\\bower_components\\Sortable\\knockout-sortable.js")
require("./..\\..\\..\\..\\..\\bower_components\\Sortable\\react-sortable-mixin.js")ploadFile = require('../../../common/upload-file.ls');
sncompleter = require('./sncompleter.ls');
postContentInitializer = require('./post-content-initializer.ls');
postCompiler = require('../views/post/smart/render.jade');
subPostCompiler = require('../views/post/smart/sub-post-render.jade');
AlbumDialog = require('./album-dialog.ls');
userCard = require('./user-card.ls');
```

これの

``` javascript
require("./..\\..\\..\\..\\..\\bower_components\\Sortable\\react-sortable-mixin.js")ploadFile = require('../../../common/upload-file.ls');
                                                                                    ^
```

でエラーになっていると思われます

**Comment by syuilo** [comment]
なぜセミコロンが付加されないのか

**Comment by syuilo** [comment]
セミコロンが付加されている行もあれば(3, 4行目など)、されていない行もある

**Comment by syuilo** [comment]
ん、セミコロンが付いてないのはどれも元のソースコードには記されていない`require`だ

**Comment by syuilo** [comment]
ということはこの`require`を生成しているやつに問題がある

**Comment by syuilo** [comment]
bower関係なのでつまりそれは**debowerify**の可能性が高い

**Comment by syuilo** [comment]
しかしdebowerify自体には`require`を吐き出すコードが含まれていないように見えます。debowerifyが間接的に利用している何か

**Comment by syuilo** [comment]
いやまて

**Comment by syuilo** [comment]
含まれてた
んで弄ってセミコロン付けるようにしたらセミコロンが付くようになった

**Comment by syuilo** [comment]
**問題はセミコロンが付かないということより次の行の文字を一部上書きしてしまうということだ**

**Comment by syuilo** [comment]
ここに問題がありそう
https://github.com/eugeneware/debowerify/blob/master/index.js#L151

**Comment by syuilo** [comment]
[debowerify](https://github.com/eugeneware/debowerify)の

``` javascript
paths.forEach(function (p, i) {
  var st = '\nrequire(' + p + ')'
  chunks[node.range[1] + (i + 1)] = st
})
```

を

``` javascript
paths.forEach(function (p, i) {
  var st = '\nrequire(' + p + ');'
  if (i === 0) {
    chunks[node.range[1] + (i + 1)] = st
  } else {
    chunks[node.range[1] + (i)] = st
  }
})
```

に書き換えたら動くようになりました。

**Comment by syuilo** [comment]
自分でも原理が判っているわけではないけどとにかくそう書き換えると正常に動く

**Comment by syuilo** [comment]
PR送ろうか悩む このバグの発生条件とか複雑そうで説明が難しいし

**Comment by syuilo** [comment]
しかしここまで突き止められたのでもうよくやったと思う

**Comment by syuilo** [comment]
疲れた

**Comment by syuilo** [comment]
https://github.com/eugeneware/debowerify/issues/81

**Comment by rinsuki** [comment]
一旦syuilo/deboowerifyを使うようにしてはどうですか
その場しのぎにはなるはずです

**Comment by syuilo** [comment]
ほむ
