### ISSUE TITLE
利用規約を見ようとするとエラー

### ISSUE THREAD

**Issue by rinsuki** [MissKernel/Misskey-Web#98]
デスクトップ版です

```
Error: /var/misskey-clone/Misskey-Web/built/sites/desktop/pages/terms-of-use/view.jade:5
    3| html(lang='ja', dir='ltr')
    4|  head
  > 5|      include ../../head
    6|      title= 'Misskey利用規約'
    7|  
    8|  body

ENOENT: no such file or directory, open '/var/misskey-clone/Misskey-Web/built/sites/desktop/head.jade'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Parser.parseInclude (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:606:18)
    at Parser.parseExpr (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:223:21)
    at Parser.block (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:729:25)
    at Parser.tag (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:838:24)
    at Parser.parseTag (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:759:17)
    at Parser.parseExpr (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:211:21)
    at Parser.block (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:729:25)
    at Parser.tag (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:838:24)
    at Parser.parseTag (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:759:17)
    at Parser.parseExpr (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:211:21)
    at Parser.parse (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/parser.js:122:25)
    at parse (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/index.js:104:21)
    at Object.exports.compile (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/index.js:205:16)
    at handleTemplateCache (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/index.js:174:25)
    at Object.exports.renderFile (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/index.js:380:10)
    at Object.exports.renderFile (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/index.js:370:21)
    at View.exports.__express [as engine] (/var/misskey-clone/Misskey-Web/node_modules/jade/lib/index.js:417:11)
    at View.render (/var/misskey-clone/Misskey-Web/node_modules/express/lib/view.js:126:8)
    at tryRender (/var/misskey-clone/Misskey-Web/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/var/misskey-clone/Misskey-Web/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/var/misskey-clone/Misskey-Web/node_modules/express/lib/response.js:961:7)
    at res.locals.display (/var/misskey-clone/Misskey-Web/built/call-controller.js:95:13)
    at module.exports (/var/misskey-clone/Misskey-Web/built/sites/desktop/pages/terms-of-use/controller.js:4:16)
    at Object.callController [as default] (/var/misskey-clone/Misskey-Web/built/call-controller.js:110:9)
    at /var/misskey-clone/Misskey-Web/built/router.js:143:34
    at Layer.handle [as handle_request] (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/layer.js:95:5)
    at /var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:330:12)
    at next (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:271:10)
    at /var/misskey-clone/Misskey-Web/built/router.js:83:13
    at Layer.handle [as handle_request] (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:312:13)
    at /var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:330:12)
    at next (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:271:10)
    at /var/misskey-clone/Misskey-Web/node_modules/subdomain/lib/subdomain.js:38:7
    at Layer.handle [as handle_request] (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:312:13)
    at /var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:330:12)
    at next (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:271:10)
    at /var/misskey-clone/Misskey-Web/built/server.js:73:5
    at Layer.handle [as handle_request] (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:312:13)
    at /var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:330:12)
    at next (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:271:10)
    at csrf (/var/misskey-clone/Misskey-Web/node_modules/csurf/index.js:100:5)
    at Layer.handle [as handle_request] (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:312:13)
    at /var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:330:12)
    at next (/var/misskey-clone/Misskey-Web/node_modules/express/lib/router/index.js:271:10)
    at MongoStore.<anonymous> (/var/misskey-clone/Misskey-Web/node_modules/express-session/index.js:432:7)
    at MongoStore.tryCatcher (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/promise.js:557:21)
    at Promise._settlePromise0 (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/promise.js:629:18)
    at /var/misskey-clone/Misskey-Web/node_modules/bluebird/js/release/nodeback.js:42:21
    at handleCallback (/var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb/lib/utils.js:96:12)
    at /var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1341:5
    at handleCallback (/var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb/lib/utils.js:96:12)
    at /var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:670:5
    at handleCallback (/var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:154:5)
    at nextFunction (/var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:675:5)
    at /var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:588:7
    at queryCallback (/var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:232:5)
    at Callbacks.emit (/var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:116:3)
    at null.messageHandler (/var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:282:23)
    at Socket.<anonymous> (/var/misskey-clone/Misskey-Web/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:273:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by rinsuki** [comment]
モバイル版でも同様の不具合が確認できました
